### ISSUE TITLE
Ability to decode memo.

### ISSUE THREAD

**Issue by Rishi556** [scientistnik/btsdex#10]
Will the ability to decode the memo come soon?

**Comment by technologiespro** [comment]
```js
let KEY = '5K...WIF';
let SENDER = 'btsUserOwnerWIFKey';

BitShares.init("wss://bitshares.openledger.info/ws");
BitShares.connect();

...

let bot = new BitShares(SENDER, KEY);
bot.setMemoKey(KEY);

...

 let memo = bot.memoDecode({
                    "from": op.op[1].memo.from,
                    "nonce": op.op[1].memo.nonce,
                    "message": op.op[1].memo.message
                }).split(':');

 console.log('memo', memo);
```

**Comment by Rishi556** [comment]
I changed it to: 

```
var memo =  
{ from: 'BTS7caZZCa1Eh6FU1eFbPa5t99Coa2xAsLB69KCr7MviwZU6jNgSa',
  to: 'BTS7NZbBawQ8qRvR9SXABCUxkwy3Tg3bGDuRnjwjokyqNmPF4tFcG',
  nonce: '392417103062207',
  message: '3cfd11f58f9c674d60fd7eb4e16b9a1d' }

  let KEY = 'WIFKEY';
  let SENDER = 'atom25';
    

  let bot = new BitShares(SENDER, KEY);
  bot.setMemoKey(KEY);
  
   let a = bot.memoDecode({
                      "from": memo.from,
                      "nonce": memo.nonce,
                      "message": memo.message
                  }).split(':');
  
   console.log('memo', a);
```

When I do that, I get: 
```
/Users/rishipanthee/Desktop/MD/node_modules/btsdex/dist/bitshares.js:415
    var feeSymbol = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : BitShares.chain.core_asset;
                                                                                                        ^

TypeError: Cannot read property 'core_asset' of undefined
    at new BitShares (/Users/rishipanthee/Desktop/MD/node_modules/btsdex/dist/bitshares.js:415:105)
    at Object.<anonymous> (/Users/rishipanthee/Desktop/MD/index.js:51:13)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
```
